specVersion: 0.2.0
name: moonriver-subql-starter
version: 1.0.0
description: Farms subquery v1
repository: ''
schema:
  file: ./schema.graphql
network:
  genesisHash: '0x401a1f9dca3da46f5c4091016c8a2f26dcea05865116b286f60f668207d1474b'
  endpoint: wss://moonriver.api.onfinality.io/public-ws
  dictionary: 'https://api.subquery.network/sq/subquery/moonriver-dictionary'
  chaintypes:
    file: "./types.yaml"
dataSources:
  - kind: substrate/Moonbeam
    startBlock: 432377
    processor:
      file: './node_modules/@subql/contract-processors/dist/moonbeam.js'
      options:
        abi: solarDistributor
        address: '0xf03b75831397D4695a6b9dDdEEA0E578faa30907'
    assets:
      solarDistributor:
        file: './abis/solarDistributor.json'
    mapping:
      file: './dist/index.js'
      handlers:
        - handler: handleDepositEvent
          kind: substrate/MoonbeamEvent
          filter:
            topics:
              - Deposit(address indexed user, uint256 indexed pid, uint256 amount)
        - handler: handleWithdrawEvent
          kind: substrate/MoonbeamEvent
          filter:
            topics:
              - Withdraw(address indexed user, uint256 indexed pid, uint256 amount)